import type { Metadata } from "next";
import { Space_Mono, Space_Grotesk } from "next/font/google";
import "./globals.css";

const Mono = Space_Mono({
  variable: "--font-space-mono",
  weight: '400',
  subsets: ['latin']
})

const Grotesk = Space_Grotesk({
  variable: "--font-space-mono",
  weight: '400',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: "VIGIL | Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${Grotesk.className} w-screen h-screen antialiased overflow-hidden`}
      >
        {children}
      </body>
    </html>
  );
}
